In [1]:
import pandas as pd
import numpy as np  
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn .datasets import load_digits
digits=load_digits()


In [2]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [3]:
sv=SVC()
sv.fit(X_train,Y_train)



SVC()

In [4]:
sv.score(X_test,Y_test)

0.987037037037037

In [5]:
lr=LogisticRegression(max_iter=100000)

lr.fit(X_train,Y_train)

LogisticRegression(max_iter=100000)

In [6]:
lr.score(X_test,Y_test)

0.9611111111111111

In [7]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [8]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9,]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [6]:
def get_score(model,X_train,X_test,Y_train,Y_test):
    model.fit(X_train,Y_train)
    return model.score(X_test,Y_test)

In [11]:
get_score(LogisticRegression(),X_train,X_test,Y_train,Y_test)

NameError: name 'LogisticRegression' is not defined

In [ ]:
from sklearn.model_selection import StratifiedKFold
skf=StratifiedKFold(n_splits=3,)


In [107]:
scores_lr=[]
scores_sv=[]
scores_rf=[]

for train_index,test_index in kf.split(digits.data):
   X_train,X_test,Y_train,Y_test=digits.data[train_index],digits.data[test_index],\
                                 digits.target[train_index],digits.target[test_index]
   print(get_score(LogisticRegression(max_iter=10000),X_train,X_test,Y_train,Y_test))
   print(get_score(SVC(),X_train,X_test,Y_train,Y_test)) 
   print(get_score(RandomForestClassifier(),X_train,X_test,Y_train,Y_test))  


0.9282136894824707
0.9666110183639399
0.9348914858096828
0.9415692821368948
0.9816360601001669
0.9465776293823038
0.9165275459098498
0.9549248747913188
0.9165275459098498


In [115]:
scores_lr=[]
scores_sv=[]
scores_rf=[]

for train_index,test_index in kf.split(digits.data):
   X_train,X_test,Y_train,Y_test=digits.data[train_index],digits.data[test_index],\
                                 digits.target[train_index],digits.target[test_index]
   scores_lr.append(get_score(LogisticRegression(max_iter=10000),X_train,X_test,Y_train,Y_test))
   scores_sv.append(get_score(SVC(),X_train,X_test,Y_train,Y_test)) 
   scores_rf.append(get_score(RandomForestClassifier(),X_train,X_test,Y_train,Y_test)) 

In [116]:
scores_lr

[0.9282136894824707, 0.9415692821368948, 0.9165275459098498]

In [117]:
scores_sv

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [118]:
scores_rf

[0.9398998330550918, 0.9515859766277128, 0.9248747913188647]

In [102]:
from sklearn.model_selection import cross_val_score

In [105]:
cross_val_score(LogisticRegression(max_iter=10000),digits.data,digits.target)

array([0.925     , 0.875     , 0.93871866, 0.93314763, 0.89693593])

In [106]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [112]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.93611111, 0.90277778, 0.94428969, 0.96100279, 0.91086351])